import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Events app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <img />
          <a href="/">Home</a>
          <a href="/events">Events</a>
          <a href="/about-us">About Us</a>
        </nav>
      </header>
      <main className={styles.main}>
        <a href="">
          <img />
          <h2>Events in London</h2>
          <p>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Vitae, id quisquam accusamus ducimus animi architecto qui distinctio, aliquid et dicta perspiciatis ab. Eaque, doloremque! Expedita.
            Vero labore, maxime illo molestiae nostrum fugit placeat id facere eius omnis reprehenderit dolore quia ducimus qui laborum? Nihil quidem at exercitationem maiores explicabo numquam.
            Mollitia laborum error, itaque consequatur facilis porro doloribus, est distinctio eum molestiae veritatis odio ipsam. Alias, repellendus! Harum expedita earum blanditiis reiciendis ducimus quibusdam id.
            Eligendi adipisci cumque totam nisi, mollitia, officiis in suscipit aliquid, voluptatem non similique provident harum? Debitis dolorum nihil, animi officiis soluta neque odio dolorem sapiente?
          </p>
        </a>
        <a href="">
          <img />
          <h2>Events in San Francisco</h2>
          <p>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Vitae, id quisquam accusamus ducimus animi architecto qui distinctio, aliquid et dicta perspiciatis ab. Eaque, doloremque! Expedita.
            Vero labore, maxime illo molestiae nostrum fugit placeat id facere eius omnis reprehenderit dolore quia ducimus qui laborum? Nihil quidem at exercitationem maiores explicabo numquam.
            Mollitia laborum error, itaque consequatur facilis porro doloribus, est distinctio eum molestiae veritatis odio ipsam. Alias, repellendus! Harum expedita earum blanditiis reiciendis ducimus quibusdam id.
            Eligendi adipisci cumque totam nisi, mollitia, officiis in suscipit aliquid, voluptatem non similique provident harum? Debitis dolorum nihil, animi officiis soluta neque odio dolorem sapiente?
          </p>
        </a>
        <a href="">
          <img />
          <h2>Events in Barcelona</h2>
          <p>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Vitae, id quisquam accusamus ducimus animi architecto qui distinctio, aliquid et dicta perspiciatis ab. Eaque, doloremque! Expedita.
            Vero labore, maxime illo molestiae nostrum fugit placeat id facere eius omnis reprehenderit dolore quia ducimus qui laborum? Nihil quidem at exercitationem maiores explicabo numquam.
            Mollitia laborum error, itaque consequatur facilis porro doloribus, est distinctio eum molestiae veritatis odio ipsam. Alias, repellendus! Harum expedita earum blanditiis reiciendis ducimus quibusdam id.
            Eligendi adipisci cumque totam nisi, mollitia, officiis in suscipit aliquid, voluptatem non similique provident harum? Debitis dolorum nihil, animi officiis soluta neque odio dolorem sapiente?
          </p>
        </a>
      </main>
      <footer className={styles.footer}>
        <p> © 2024 Time to Code - A Project Built with Next.js</p>
      </footer>
    </div>
  );
}
